package org.usvm.utils

import ai.onnxruntime.OnnxTensor
import ai.onnxruntime.OnnxTensor.createTensor
import ai.onnxruntime.OrtEnvironment
import ai.onnxruntime.OrtSession
import org.usvm.StateId
import org.usvm.logger
import org.usvm.statistics.BasicBlock
import org.usvm.statistics.BlockGraph
import org.usvm.util.OnnxModel
import java.nio.FloatBuffer
import java.nio.LongBuffer
import kotlin.collections.toLongArray

data class PathConditionVertex(
    val id: Int,
    val type: Int,
    val children: List<Int>,
)

enum class Mode {
    CPU, GPU
}

data class AIGameStep<T : BasicBlock>(
    val Game: Game<T>, val NNOutput: Array<FloatArray>
) {
    // autogenerated
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as AIGameStep<*>

        if (Game != other.Game) return false
        if (!NNOutput.contentDeepEquals(other.NNOutput)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = Game.hashCode()
        result = 31 * result + NNOutput.contentDeepHashCode()
        return result
    }
}

class OnnxModelImpl<Block : BasicBlock>(
    pathToONNX: String, mode: Mode, val isTrainMode: Boolean, val saveStep: (AIGameStep<Block>) -> Unit = {}
) : OnnxModel<Game<Block>> {
    private val env: OrtEnvironment = OrtEnvironment.getEnvironment()
    private val sessionOptions: OrtSession.SessionOptions = OrtSession.SessionOptions().apply {
        if (mode == Mode.GPU) {
            addCUDA()
        } else {
            logger.info("Using CPU execution provider.")
        }
    }
    private val session: OrtSession = env.createSession(pathToONNX, sessionOptions)
    lateinit var gameState: Game<Block>

    override fun predictState(game: Game<Block>): UInt { // game=delta!!!
        gameState = if (!::gameState.isInitialized) {
            game
        } else {
            val pcIds = gameState.pathConditionVertices.map { it.id }
            Game(
                vertices = gameState.vertices,
                stateWrappers = gameState.stateWrappers,
                blockGraph = game.blockGraph,
                pathConditionVertices = gameState.pathConditionVertices.toMutableList().also {
                    for (pc in game.pathConditionVertices) {
                        if (!pcIds.contains(pc.id)) {
                            it.add(pc)
                        }
                    }
                })
        }
        val stateIds = mutableMapOf<StateId, Int>()
        val input = generateInput(gameState, stateIds)
        val output = session.run(input)
        val predictedStates = output["out"].get().value as Array<*>
        val predictedStatesRanks = predictedStates.map { (it as FloatArray).toList() }
        saveStep(AIGameStep(game, predictedStates.map { it as FloatArray }.toTypedArray()))
        return checkNotNull(getPredictedState(predictedStatesRanks, stateIds))
    }

    private fun generateInput(
        game: Game<Block>, stateIds: MutableMap<StateId, Int>
    ): Map<String, OnnxTensor> {
        val (vertices, stateWrappers, blockGraph, pathConditionVertices) = game
        val vertexIds = mutableMapOf<Int, Int>()
        val gameVertices = tensorFromBasicBlocks(vertices, vertexIds)
        val states = tensorFromStates(stateWrappers, stateIds)
        val (vertexToVertexEdgesIndex, vertexToVertexEdgesAttributes) = tensorFromVertexEdges(
            vertices, blockGraph, vertexIds
        )
        val (parentOfEdges, historyEdgesIndexVertexToState, historyEdgesAttributes) = tensorFromStateEdges(
            stateWrappers, stateIds, vertexIds
        )
        val vertexToState = tensorFromStatePositions(stateWrappers, stateIds, vertexIds)
        fun createPCMap(pathConditionVertices: Collection<PathConditionVertex>): Map<Int, Int> {
            val pcMap = mutableMapOf<Int, Int>()
            for ((index, vertex) in pathConditionVertices.filter { stateIds.containsKey(it.id.toUInt()) }.withIndex()) {
                pcMap[vertex.id] = index
            }
            return pcMap
        }

        fun createStateMap(states: Collection<StateWrapper<*, *, *>>): Map<Int, Int> {
            val stateMap = mutableMapOf<Int, Int>()
            for ((index, state) in states.withIndex()) {
                stateMap[state.id.toInt()] = index
            }
            return stateMap
        }

        val stateMap = createStateMap(stateWrappers)
        val pcMap = createPCMap(pathConditionVertices)
        val (pcv, pcvToPCV) = createPathConditionTensors(
            pathConditionVertices, pcMap
        )
        val pcvToSV = createPathConditionStateTensors(stateWrappers, pcMap, stateMap)

        return mapOf(
            "game_vertex" to gameVertices,
            "state_vertex" to states,
            "path_condition_vertex" to pcv,
            "gamevertex_to_gamevertex_index" to vertexToVertexEdgesIndex,
            "gamevertex_to_gamevertex_type" to vertexToVertexEdgesAttributes,
            "gamevertex_history_statevertex_index" to historyEdgesIndexVertexToState,
            "gamevertex_history_statevertex_attrs" to historyEdgesAttributes,
            "gamevertex_in_statevertex" to vertexToState,
            "statevertex_parentof_statevertex" to parentOfEdges,
            "pathconditionvertex_to_pathconditionvertex" to pcvToPCV,
            "pathconditionvertex_to_statevertex" to pcvToSV,
        )
    }

    private fun getPredictedState(stateRank: List<List<Float>>, stateIds: Map<StateId, Int>): StateId? {
        return stateRank.mapIndexed { index, ranks -> stateIds.entries.find { it.value == index }?.key to ranks.sum() }
            .maxBy {
                if (it.first == null) {
                    Float.NEGATIVE_INFINITY
                } else {
                    it.second
                }
            }.first
    }

    private fun tensorFromBasicBlocks(vertices: Collection<Block>, vertexIds: MutableMap<Int, Int>): OnnxTensor {
        val numOfVertexAttributes = 7
        val verticesArray = vertices.flatMapIndexed { i, vertex ->
            vertexIds[vertex.id] = i
            listOf(
                vertex.inCoverageZone.toFloat(),
                vertex.basicBlockSize.toFloat(),
                vertex.coveredByTest.toFloat(),
                vertex.visitedByState.toFloat(),
                vertex.touchedByState.toFloat(),
                vertex.containsCall.toFloat(),
                vertex.containsThrow.toFloat()
            )
        }.toFloatArray()

        return createFloatTensor(verticesArray, vertices.size, numOfVertexAttributes)
    }

    private fun tensorFromStates(
        states: Collection<StateWrapper<*, *, *>>, stateIds: MutableMap<StateId, Int>
    ): OnnxTensor {
        val numOfStateAttributes = 6
        val statesArray = states.flatMapIndexed { i, state ->
            stateIds[state.id] = i
            listOf(
                state.position,
                state.visitedAgainVertices,
                state.visitedNotCoveredVerticesInZone,
                state.visitedNotCoveredVerticesOutOfZone,
                state.stepWhenMovedLastTime,
                state.instructionsVisitedInCurrentBlock
            ).map { it.toFloat() }
        }.toFloatArray()

        return createFloatTensor(statesArray, states.size, numOfStateAttributes)
    }

    private fun tensorFromVertexEdges(
        blocks: Collection<Block>, blockGraph: BlockGraph<*, Block, *>, vertexIds: MutableMap<Int, Int>
    ): Pair<OnnxTensor, OnnxTensor> {
        val vertexFrom = mutableListOf<Long>()
        val vertexTo = mutableListOf<Long>()
        val attributes = mutableListOf<Long>()
        var edgeId = 0L

        blocks.forEach { block ->
            blockGraph.successors(block).forEach { successor ->
                vertexFrom.add(vertexIds[block.id]?.toLong() ?: -1)
                vertexTo.add(vertexIds[successor.id]?.toLong() ?: -1)
                attributes.add(edgeId++)
            }
        }

        val indexList = (vertexFrom + vertexTo).toLongArray()
        return createLongTensor(indexList, 2, vertexFrom.size) to createLongTensor(
            attributes.toLongArray(), attributes.size
        )
    }

    private fun tensorFromStateEdges(
        states: Collection<StateWrapper<*, *, *>>, stateIds: MutableMap<StateId, Int>, vertexIds: MutableMap<Int, Int>
    ): Triple<OnnxTensor, OnnxTensor, OnnxTensor> {
        val numOfParentOfEdges = states.sumOf { it.children.size }
        val numOfHistoryEdges = states.sumOf { it.history.size }
        val numOfHistoryEdgeAttributes = 2

        val parentOf = LongArray(2 * numOfParentOfEdges)
        val historyIndexVertexToState = LongArray(2 * numOfHistoryEdges)
        val historyAttributes = LongArray(numOfHistoryEdges * numOfHistoryEdgeAttributes)

        states.forEach { state ->
            state.children.forEachIndexed { i, child ->
                parentOf[i] = stateIds[state.id]?.toLong() ?: -1
                parentOf[numOfParentOfEdges + i] = stateIds[child.id]?.toLong() ?: -1
            }

            var historyIndex = 0
            var historyAttrsIndex = 0
            state.history.forEach { (_, historyElem) ->
                historyIndexVertexToState[historyIndex] = vertexIds[historyElem.blockId]?.toLong() ?: -1
                historyIndexVertexToState[numOfHistoryEdges + historyIndex] = stateIds[state.id]?.toLong() ?: -1
                historyAttributes[historyAttrsIndex] = historyElem.numOfVisits.toLong()
                historyAttributes[historyAttrsIndex + 1] = historyElem.stepWhenVisitedLastTime.toLong()
                historyAttrsIndex += numOfHistoryEdgeAttributes
                historyIndex++
            }
        }

        val parentTensor = createLongTensor(parentOf, 2, numOfParentOfEdges)
        val historyIndexTensor = createLongTensor(historyIndexVertexToState, 2, numOfHistoryEdges)
        val historyAttributesTensor = createLongTensor(
            historyAttributes, numOfHistoryEdges, numOfHistoryEdgeAttributes
        )
        return Triple(parentTensor, historyIndexTensor, historyAttributesTensor)
    }

    private fun tensorFromStatePositions(
        states: Collection<StateWrapper<*, *, *>>, stateIds: MutableMap<StateId, Int>, vertexIds: MutableMap<Int, Int>
    ): OnnxTensor {
        val totalStates = states.size
        val vertexToState = LongArray(2 * totalStates)
        states.forEachIndexed { i, state ->
            val stateIndex = stateIds[state.id]
            val vertexIndex = vertexIds[state.position]?.toLong() ?: -1

            vertexToState[i] = vertexIndex
            if (stateIndex != null) {
                vertexToState[stateIndex + i] = stateIndex.toLong()
            }
        }
        return createLongTensor(vertexToState, 2, totalStates)
    }

    fun createPathConditionTensors(
        pathConditionVertices: Collection<PathConditionVertex>, pcMap: Map<Int, Int>
    ): Pair<OnnxTensor, OnnxTensor> {
        val pcLength = 49

        val pcFeatures = mutableListOf<FloatArray>()
        for (vertex in pathConditionVertices) {
            val oneHot = FloatArray(pcLength) { 0f }
            oneHot[vertex.type] = 1f
            pcFeatures.add(oneHot)
        }
        val pcEdges = mutableListOf<LongArray>()
        for (vertex in pathConditionVertices) {
            for (childId in vertex.children) {
                val fromIdx = pcMap[vertex.id]!!
                val toIdx = pcMap[childId]!!
                pcEdges.add(longArrayOf(fromIdx.toLong(), toIdx.toLong()))
                pcEdges.add(longArrayOf(toIdx.toLong(), fromIdx.toLong()))
            }
        }

        val featuresBuffer = FloatBuffer.allocate(pcFeatures.size * pcLength).apply {
            for (feature in pcFeatures) {
                put(feature)
            }
            rewind()
        }

        val edgesBuffer = if (pcEdges.isNotEmpty()) {
            LongBuffer.allocate(pcEdges.size * 2).apply {
                for (edge in pcEdges) {
                    put(edge[0])
                    put(edge[1])
                }
                rewind()
            }
        } else {
            LongBuffer.wrap(LongArray(0))
        }
        return Pair(
            createTensor(
                env, featuresBuffer, longArrayOf(pcFeatures.size.toLong(), pcLength.toLong())
            ), createTensor(
                env, edgesBuffer, longArrayOf(2, pcEdges.size.toLong())
            )
        )
    }

    fun createPathConditionStateTensors(
        states: Collection<StateWrapper<*, *, *>>, pcMap: Map<Int, Int>, stateMap: Map<Int, Int>
    ): OnnxTensor {
        val pcToStateEdges = mutableListOf<LongArray>()
        for (stateWrapper in states) {
            val pcId = stateWrapper.pathConditionVertex.id
            val stateId = stateWrapper.id.toInt()

            val pcIndex = pcMap[pcId] ?: continue
            val stateIndex = stateMap[stateId] ?: continue

            if (pcIndex < pcMap.size && stateIndex < stateMap.size) {
                pcToStateEdges.add(longArrayOf(pcIndex.toLong(), stateIndex.toLong()))
            }
        }

        val pcToStateTensor = createEdgeTensor(pcToStateEdges)
        return pcToStateTensor
    }

    fun createEdgeTensor(edges: List<LongArray>): OnnxTensor {
        val edgesSize = if (edges.isEmpty()) 0 else edges.size
        val buffer = LongBuffer.allocate(edgesSize * 2).apply {
            for (edge in edges) {
                put(edge[0])
                put(edge[1])
            }
            rewind()
        }
        return createTensor(env, buffer, longArrayOf(2, edgesSize.toLong()))
    }

    private fun createFloatTensor(data: FloatArray, vararg numbers: Int): OnnxTensor {
        val shape = createShape(*numbers)
        val buffer = FloatBuffer.wrap(data)
        return OnnxTensor.createTensor(env, buffer, shape)
    }

    private fun createLongTensor(data: LongArray, vararg numbers: Int): OnnxTensor {
        val shape = createShape(*numbers)
        val buffer = LongBuffer.wrap(data)
        return OnnxTensor.createTensor(env, buffer, shape)
    }

    private fun createShape(vararg numbers: Int) = numbers.map { it.toLong() }.toLongArray()

    private fun Boolean.toFloat() = if (this) 1f else 0f
}
